/**
 * Playground token generator (temporary — replaced by the plugin's runtime
 * injection in Phase 4). Computes the real theme engine's `--pt-*` custom
 * properties for a given accent and writes them into the marked block of
 * `custom.scss`, so the tokens can never drift from the engine.
 *
 *   pnpm theme:tokens             # uses the default accent
 *   pnpm theme:tokens '#2563eb'   # any hex
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

import { buildTheme, themeToCss } from '../src/theme/index'

const DEFAULT_ACCENT = '#e30613'
const START = '/* PT-TOKENS:START — generated by `pnpm theme:tokens`; do not edit by hand */'
const END = '/* PT-TOKENS:END */'

const dirname = path.dirname(fileURLToPath(import.meta.url))
const cssPath = path.resolve(dirname, '../src/app/(payload)/custom.scss')

const accent = process.argv[2] ?? DEFAULT_ACCENT
const tokens = themeToCss(buildTheme(accent)) // throws on invalid accent, with a clear message

const source = readFileSync(cssPath, 'utf8')
const startIdx = source.indexOf(START)
const endIdx = source.indexOf(END)
if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
  throw new Error(`Could not find the PT-TOKENS markers in ${cssPath}. Add them before generating.`)
}

const before = source.slice(0, startIdx)
const after = source.slice(endIdx + END.length)
const next = `${before}${START}\n${tokens}\n${END}${after}`

writeFileSync(cssPath, next)
console.log(`Wrote ${accent} tokens into ${path.relative(process.cwd(), cssPath)}`)
